version: "3.7"
services:
  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
      no_cache: true
    ports:
      - $WORDPRESS_PORT:80
    environment:
      WORDPRESS_DB_HOST: db:$MYSQL_PORT
      WORDPRESS_DB_USER: $WORDPRESS_DB_USER
      WORDPRESS_DB_PASSWORD: $WORDPRESS_DB_PASSWORD
      WORDPRESS_DB_NAME: $WORDPRESS_DB_NAME
      WORDPRESS_TITLE: $WORDPRESS_TITLE
      WORDPRESS_ADMIN_USER : $WORDPRESS_ADMIN_USER
      WORDPRESS_ADMIN_PASSWORD : $WORDPRESS_ADMIN_PASSWORD
      WORDPRESS_ADMIN_EMAIL : $WORDPRESS_ADMIN_EMAIL
      WORDPRESS_URL : $WORDPRESS_HOSTNAME
    volumes:
      - ./wordpress:/var/www/html
  db:
    image: mysql:latest
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - $MYSQL_PORT:3306
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $WORDPRESS_DB_NAME
      MYSQL_USER: $WORDPRESS_DB_USER
      MYSQL_PASSWORD: $WORDPRESS_DB_PASSWORD