name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

    build_push:

        runs-on: ubuntu-latest

        steps:
          - name: Checkout the repository
            uses: actions/checkout@v3
          - name: Show the version
            env: 
                DOCKER_IMAGE_VERSION: ${{ secrets.DOCKER_IMAGE_VERSION }}
            run: |
                echo "Current version: $DOCKER_IMAGE_VERSION"
          - name: Get the version
            run: |
                chmod +x .github/scripts/version.sh
                ./.github/scripts/version.sh
          - name: Build the Docker image
            run: docker build . --file Dockerfile --tag wordpress-unattended:v$DOCKER_IMAGE_VERSION
          - name: Login to DockerHub
            uses: docker/login-action@v1
            with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
          - name: Tag the Docker image
            run: docker tag wordpress-unattended:v$DOCKER_IMAGE_VERSION ${{ secrets.DOCKER_USERNAME }}/wordpress-unattended:v$DOCKER_IMAGE_VERSION
          - name: Push the Docker image
            run: docker push ${{ secrets.DOCKER_USERNAME }}/wordpress-unattended:v$DOCKER_IMAGE_VERSION