name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

    build:

        runs-on: ubuntu-latest

        steps:
          - name: Checkout the repository
            uses: actions/checkout@v3
          - name: Show the version
            env: 
                DOCKER_IMAGE_VERSION: ${{ secrets.DOCKER_IMAGE_VERSION }}
            run: |
                echo "Current version: $DOCKER_IMAGE_VERSION"
          - name: Get the version
            run: |
                chmod +x .github/scripts/version.sh
                ./.github/scripts/version.sh
          - name: Build the Docker image
            run: docker build . --file Dockerfile --tag wordpress-unattended:v$DOCKER_IMAGE_VERSION

    push:
        needs: build
    
        runs-on: ubuntu-latest
    
        steps:
            - name: Push the Docker image
              run: |
                docker tag wordpress-unattended:v${{ secrets.DOCKER_IMAGE_VERSION }} ${{ secrets.DOCKER_USERNAME }}/wordpress-unattended:v${{ secrets.DOCKER_IMAGE_VERSION }}
                echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
                docker push ${{ secrets.DOCKER_USERNAME }}/wordpress-unattended:v${{ secrets.DOCKER_IMAGE_VERSION }}
